services:
  mattermost:
    image: mattermost/mattermost-preview
    ports:
      - "${MATTERAIO_MM_HTTP_PORT:-8065}:8065"
    environment:
      MM_TEAMSETTINGS_ENABLEUSERCREATION: "true"
      MM_TEAMSETTINGS_ENABLEOPENSERVER: "true"
      MM_EMAILSETTINGS_ENABLESIGNUPWITHEMAIL: "true"
      MM_EMAILSETTINGS_ENABLESIGNINWITHEMAIL: "true"
      MM_EMAILSETTINGS_ENABLESIGNINWITHUSERNAME: "true"
      MM_EMAILSETTINGS_REQUIREEMAILVERIFICATION: "false"
